
// SUBROUTINE TO READ SEAM PARAMETER FILE AND SAVE VARIABLES IN COMMON.







// line 1 JOBNAME


// LINE 2 ECHO PRINT


// LINE 3 FREQUENCY AND BANDWIDTH

// LINE 4 TRANSIENT PARAMETERS

// LINE 5 OUTPUT UNITS

// LINE 6 STRUCTURAL MOTION QUANTITY AND REFERENCE


// LINE 7 ACOUSTIC SPACE QUANTITY AND REFERENCE

// LINE 8 COUPLING MATRIX PRINT FLAG AND COUPLING INFORMATION TO SET COUPLING MULTIPLICATION FACTOR (TAUMUL)

// LINE 9 POWER FLOW PRINT FLAG

// LINE 10 SELECTED SUBSYSTEM PRINT FLAG

// LINE 11 SELECTED JUNCTION PRINT FLAG

// LINE 12 (OPTIONAL) POWER, ENERGY, & INTENSITY REFERENCES

// LINE 13  dB RESPONSE TABLE ACCURACY, lin RESPONSE TABLE ACCURACY

// SUCCESSFUL READ OF PARAM FILE